
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario 1
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }
    public String BuscarInfo1(short tamanioA, RandomAccessFile a, String tipo){
        String etiqueta="";
        try {
            boolean info=false;
            a.seek(10);
            for(int i=0; i<tamanioA;i++){
                if(!etiqueta.contains(tipo)){
                    etiqueta=etiqueta+ (char)a.readByte();
                }
                else{
                    info=true;
                    break;
                }
            }
            if(info){
                int tamanioDato=0;
                for(int i=0; i<4;i++){
                    tamanioDato=tamanioDato + a.readByte();
                }
                byte margen=0;
                for(int i=0; i<2;i++){
                    margen=(byte) (margen + a.readByte());
                }
                if(margen==0){
                    etiqueta="";
                    for(int i=0; i<tamanioDato;i++){
                        etiqueta=etiqueta + (char)a.readByte();
                    }
                }
            }
            else{
                etiqueta="-------";
            }
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        return etiqueta;
    }
    
    public String BuscarInfo2(short tamanioA, RandomAccessFile a){
        String etiqueta="";        
        try {
            boolean info=false;
            a.seek(10);
            for(int i=0; i<tamanioA;i++){
                if(!etiqueta.contains("COMM")){
                    etiqueta=etiqueta + (char)a.readByte();
                }
                else{
                    info=true;
                    break;
                }
            }
            if(info){
                int tamanioDato=0;
                for(int i=0; i<4;i++){
                    tamanioDato=tamanioDato + a.readByte();
                }
                byte margen=0;
                for(int i=0; i<2;i++){
                    margen=(byte) (margen + a.readByte());
                }
                if(margen==0){
                    a.skipBytes(5);
                    etiqueta="";
                    for(int i=0; i<tamanioDato-5;i++){
                        etiqueta=etiqueta + (char)a.readByte();
                    }
                }
            }
            else{
                etiqueta="-------";
            }
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        return etiqueta;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        try {
            // TODO add your handling code here:
            FileInputStream archivo = new FileInputStream(jFileChooser1.getSelectedFile().getPath());
            RandomAccessFile a = new RandomAccessFile("auxiliar.dat", "rw");
            for(int i=0;i<3;i++){
                a.write(archivo.read());
            }
            a.seek(0);
            String etiqueta="";
            for(int i=0; i<3;i++){
                etiqueta=etiqueta+a.readByte();
            }
            if(etiqueta.equals("736851")){
                a.write(archivo.readAllBytes());
                etiqueta="";
                a.seek(0);
                for(int i=0; i<3;i++){
                    etiqueta=etiqueta + (char)a.readByte();
                }
                etiqueta+="v2";
                for(int i=0; i<2;i++){
                    etiqueta=etiqueta +"."+ a.readByte();
                }
                if(etiqueta.equals("ID3v2.3.0")){
                    if(a.readByte()==0){
                        //No necesita desincronizacion??
                        etiqueta="";
                        ////////////////////TAMAÑO DEL ARCHIVO////////////////////
                        long aux;
                        for(int i=0;i<4;i++){
                            aux = a.readByte();
                            String binario = Long.toBinaryString(aux);
                            while(binario.length()!=7){
                                binario="0"+binario;
                            }
                            etiqueta=etiqueta+binario;
                        }
                        short tamanioA=0;
                        for(int i=0;i<8;i++){
                            if(etiqueta.charAt(etiqueta.length()-1-i)=='1'){
                                tamanioA = (short) (tamanioA + Math.pow(2, i));
                            }
                        }
                        jTextArea1.removeAll();
                        etiqueta="Titulo:   " + BuscarInfo1(tamanioA, a, "TIT2");
                        jTextArea1.append(etiqueta);
                        etiqueta="Album:   " + BuscarInfo1(tamanioA, a, "TALB");
                        jTextArea1.append(etiqueta);
                        etiqueta="Cantante:   " + BuscarInfo1(tamanioA, a, "TPE1");
                        jTextArea1.append(etiqueta);
                        etiqueta="Año:   " + BuscarInfo1(tamanioA, a, "TYER");
                        jTextArea1.append(etiqueta);
                        etiqueta="Info:   " + BuscarInfo2(tamanioA, a);
                        jTextArea1.append(etiqueta);
                    }
                }
            }
            else{
                jTextArea1.removeAll();
                jTextArea1.setText("No es un archivo mp3");
            }
            archivo.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
