
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario 1
 */
public class Mostrar extends javax.swing.JFrame {
    ArrayList<Cancion> canciones=new ArrayList();
    DefaultTableModel tabla = new DefaultTableModel();
    DefaultListModel lista = new DefaultListModel();
    /**
     * Creates new form Mostrar
     */
    public Mostrar() {
        tabla.addColumn("Artista");
        tabla.addColumn("Album");
        tabla.addColumn("Pista");
        initComponents();
        agregar();
    }
    public void agregar(){
        leer(4);
        for(int i=0; i<canciones.size(); i++){
            tabla.addRow(new Object[]{canciones.get(i).getArtista(),canciones.get(i).getAlbum(), canciones.get(i).getPista()});
        }
        jTable1.setModel(tabla);
    }

    public String leerDato(RandomAccessFile archivo, int puntero, boolean extra){
        String dato="";
        try {
            int tamanio;
            archivo.seek(puntero);
            if(extra){
                tamanio=archivo.readInt();
            }
            else{
                tamanio=archivo.readByte();
            }
            for(int i=0; i<tamanio; i++){
                dato=dato+(char)archivo.readByte();
            }
        } catch (IOException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dato;
    }
    
    public void leer(int puntero){
        //Primer puntero es 4
        int punteroAlmacen=0;
        int fin=0;
        try {
            RandomAccessFile a = new RandomAccessFile("Almacen.data", "rw");
            RandomAccessFile indx = new RandomAccessFile("Indice.data", "rw");
            RandomAccessFile info = new RandomAccessFile("Informacion.data", "rw");
            RandomAccessFile letra = new RandomAccessFile("Letras.data", "rw");
            Cancion cancion = new Cancion();
            a.seek(puntero);
            int punteroAuxiliar=puntero;
            if(puntero==4){
                for(int i=0;i<5;i++){
                    punteroAuxiliar=a.readInt();
                    a.seek(punteroAuxiliar);
                }
            }
            a.skipBytes(4);
            punteroAlmacen=a.readInt();
            cancion.setPista(leerDato(indx, a.readShort(), false));
            cancion.setDisquera(leerDato(a, a.readInt(),false));
            punteroAuxiliar+=14;
            a.seek(punteroAuxiliar);
            cancion.setArtista(leerDato(indx, a.readShort(),false));
            cancion.setAlbum(leerDato(a, a.readInt(),false));
            punteroAuxiliar+=6;
            a.seek(punteroAuxiliar);
            indx.seek(a.readShort());
            cancion.setAnio(indx.readShort());
            punteroAuxiliar+=2;
            a.seek(punteroAuxiliar);
            cancion.setGenero(leerDato(a, a.readInt(),false));
            punteroAuxiliar+=4;
            a.seek(punteroAuxiliar);
            cancion.setDireccion(leerDato(a, a.readInt(),false));
            punteroAuxiliar+=4;
            a.seek(punteroAuxiliar);
            cancion.setDuracion(a.readShort());
            cancion.setEnlaceArtista(leerDato(a, a.readInt(),false));
            punteroAuxiliar+=6;
            a.seek(punteroAuxiliar);
            cancion.setEnlaceDisquera(leerDato(a, a.readInt(),false));
            punteroAuxiliar+=4;
            a.seek(punteroAuxiliar);
            cancion.setEnlaceOtros(leerDato(a, a.readInt(),false));
            punteroAuxiliar+=4;
            a.seek(punteroAuxiliar);
            cancion.setInfo(leerDato(info, a.readInt(),true));
            cancion.setLetra(leerDato(letra, a.readInt(),true));
            canciones.add(cancion);
            a.seek(punteroAlmacen);
            fin=a.readInt();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(fin!=0 && punteroAlmacen!=0){
            leer(punteroAlmacen);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Almacén de Música");
        setAlwaysOnTop(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artista", "Álbum", "Pista"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cancion s =canciones.get(jTable1.getSelectedRow());
        lista.clear();
        lista.addElement("Pista:    "+s.getPista());
        lista.addElement("Duración: "+s.getDuracion());
        lista.addElement("Artista:  "+s.getArtista());
        lista.addElement("Álbum:    "+s.getAlbum());
        lista.addElement("Disquera: "+s.getDisquera());
        lista.addElement("Año:  "+s.getAnio());
        lista.addElement("Genero:   "+s.getGenero());
        lista.addElement("Dirección:    "+s.getDireccion());
        lista.addElement("Enlace del Artista:   "+s.getEnlaceArtista());
        lista.addElement("Enlace de la Disquera:   "+s.getEnlaceDisquera());
        lista.addElement("Otros Enlaces:   "+s.getEnlaceOtros());
        lista.addElement("Información:  "+s.getInfo());
        lista.addElement("Letra:    "+s.getLetra());
        jList1.setModel(lista);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
